### ISSUE TITLE
journeymap에서 waypoint 한글 적을 때, 한글 자모가 분리되는 현상

### ISSUE THREAD

**Issue by shihyeon** [najoan125/fabric-koreanchat#1]
v 1.3.1-1.3.4 모두 journeymap에서 한글 자모를 기록할 때 분리되는 현상이 있습니다.

ps. curseforge 말고 modrinth에도 커밋 가능한가요?

**Comment by najoan125** [comment]
다른 모드에서 문제가 발생하는 경우에는 현실적으로 해결하기 어렵지만, 최대한 오픈소스 등을 참고하여 해결해보도록 하겠습니다!

modrinth에는 커밋해 본 적은 없지만 시도는 해보겠습니다..!

**Comment by shihyeon** [comment]
다른 한글채팅 모드에는 xreros minimap api를 사용하여 해결한 것 같더라고요. (이걸로 설정했음에도 journeymap에서 문제가 없었어요.)

```kotlin
repositories {
    maven { url "https://api.modrinth.com/maven" }
}

dependencies {
    modCompileOnly "maven.modrinth:xaeros-minimap:${xaeros_minimap_version}"
}
```

혹은 [journeymap-api](https://github.com/TeamJM/journeymap-api/blob/1_20x_2.0/docs/howto.md)도 있는 것 같아요.

```kotlin
repositories {
    // JourneyMap API releases are here
    maven {
        name = "JourneyMap (Public)"
        url = "https://jm.gserv.me/repository/maven-public/"
    }
    maven {
        url "https://www.cursemaven.com"
    }
}

// FABRIC/QUILT
dependencies {
    modCompileOnlyApi group: 'info.journeymap', name: 'journeymap-api', version: project.journeymap_api_version_fabric, changing: true
    modRuntimeOnly "curse.maven:journeymap-${project.jm_project_id}:${project.fabric_jm_file_id}"
}
```

**Comment by shihyeon** [comment]
저니맵 개발자한테 질문하고, 좀 여러 테스트를 해보니, 호환성 문제가 아닙니다.

Mixin TextFieldWidget에서 버그를 수정해야 한다고 합니다.

아래 영상을 보시면 한글을 입력할 때, color-code에도 입력이 되는 모습을 볼 수 있습니다.
(제가 보기에는 텍스트박스 전부를 선택하는 것 같습니다.)
(location은 int이므로 문자열 입력이 안 되고, 컬러는 입력이 됩니다.)
(커서가 가리키는 텍스트박스만 입력이 되게 하는 방법을 구현해야 할 것 같습니다.)
(마인크래프트 다른 입력 창들이 다 한 텍스트박스만 있었기에 이 버그를 발견하지 못 한 것 같습니다.)

이를 해결할 수 있으면 좋겠습니다.
(후원이 가능하다면 하고 싶네요)


https://github.com/najoan125/fabric-koreanchat/assets/76618619/3068f43f-e2ac-4299-9765-1c2bdd6b2cc6

**Comment by najoan125** [comment]
이 모드를 개선하기 위해 노력해주셔서 감사합니다. 앞서 말씀하신 내용들을 근거로 해서 문제를 해결해보도록 하겠습니다! 
후원 기능은 조만간 모드 내에 추가할 예정입니다(언제 추가될 지 모르며, 추가되지 않을 수도 있습니다) 혹시 토스 앱이 깔려있다면 토스 아이디 https://toss.me/najoan 으로 후원하셔도 됩니다!
