### ISSUE TITLE
 reeses-sodium-options search box 호환성

### ISSUE THREAD

**Issue by shihyeon** [najoan125/fabric-koreanchat#11]
reeses-sodium-options의 search box에 한글채팅을 입력하기 위해 [SearchTextFieldComponent](https://github.com/FlashyReese/reeses-sodium-options/blob/1.21/dev/src/main/java/me/flashyreese/mods/reeses_sodium_options/client/gui/frame/components/SearchTextFieldComponent.java)을 [TextFieldWidgetMixin](https://github.com/najoan125/fabric-koreanchat/blob/1.21/src/main/java/com/hyfata/najoan/koreanpatch/mixin/TextFieldWidgetMixin.java)처럼 Mixin해야 하는 건가요?

![image](https://github.com/najoan125/fabric-koreanchat/assets/76618619/621a2d2c-47a3-4b05-bf31-5e9135714039)

따로 SearchTextFieldComponent에 TextFieldWidgetMixin이 적용되게 할 수는 없나요? SearchTextFieldComponent에 한글 유틸을 모두 구현하는 것보다 TextFieldWidgetMixin이 적용되면 좋을텐데, TextFieldWidget과 구조가 다르니 어려우려나요?

아니면 설정 창에서는 IME를 키게 만들 수 있나요?

**Comment by shihyeon** [comment]
modnemu의 search box도 마찬가지인 걸 보니 호환성 얻는 것은 어려워 보이네요...
![image](https://github.com/najoan125/fabric-koreanchat/assets/76618619/70d77aff-558d-4334-aedf-b1ecea3dc53c)

**Comment by najoan125** [comment]
아 그것도 이미 인지 하고 있었습니다. 조만간 고치도록 하겠습니다!

**Comment by najoan125** [comment]
Win key + . 을 누르거나 모드에서 지원하지 않는 GUI가 열리면 IME를 자동으로 활성화 하는 기능을 추가할 계획을 가지고 있습니다. 하지만 IME를 비활성화한 후 다시 활성화 하는 방법을 찾지 못하여, 찾는 중에 있습니다. 그리고 IME 비활성화하지 않고 한/영키 전환을 다른 키로 할 수 있도록 하는 설정 기능도 추가 예정에 있습니다.

**Comment by shihyeon** [comment]
수정되었기에 이슈 닫겠습니다.
https://github.com/najoan125/fabric-koreanchat/commit/1889c6d03f8909a6c4d76ee41d139a323ad557a7
