### ISSUE TITLE
백포팅 빌드 자바 버전 문제

### ISSUE THREAD

**Issue by shihyeon** [najoan125/fabric-koreanchat#19]
https://github.com/Shihyeon/fabric-koreanchat/commit/700daee5459dc30fe2b746545c30fef18c71e94f

20.6 -> 20.4 백포팅할 때 자바 버전도 같이 안 바꾸신 듯 합니다.

**Comment by najoan125** [comment]
앗 깜빡했네요 곧 수정하겠습니다
