### ISSUE TITLE
마인크래프트 1.20.1 버전용 koreanchat 1.6.0 버전이 modmenu 7.2.2버전과 충돌

### ISSUE THREAD

**Issue by Merhaf** [najoan125/fabric-koreanchat#21]
**gpt에 분석을 요청했습니다.**

이 Minecraft 크래시 리포트는 게임 시작 과정에서 오류가 발생했음을 나타냅니다. 주요 문제는 modmenu 모드와 관련된 믹스인(Mixin) 오류로 보입니다. 문제의 원인은 koreanpatch 모드가 modmenu의 ModsScreen 클래스에 대한 믹스인 적용을 시도했지만, 해당 클래스에서 지정한 'render' 타겟을 찾을 수 없다는 것입니다.

자세히 설명하자면:

기본 오류: modmenu 모드가 클라이언트 초기화 단계에서 오류를 일으켰습니다. 이로 인해 Minecraft가 제대로 시작되지 못했습니다.

원인: koreanpatch 모드의 믹스인이 com.terraformersmc.modmenu.gui.ModsScreen 클래스에 적용될 때, 'render'라는 메서드 타겟을 찾지 못했습니다. 이로 인해 MixinApplyError가 발생했습니다.

세부 사항:

MixinProcessor가 믹스인을 적용하는 과정에서 오류가 발생했습니다.
@Inject 애너테이션이 지정한 메서드나 위치를 찾지 못했습니다.
koreanpatch.mixins.json에서 지정된 믹스인 설정에 문제가 있는 것으로 보입니다.

**Comment by najoan125** [comment]
지금 확인해보니까 1.6.0 버전 전체적으로 CommandBlock IDE와 Modmenu가 호환되지 않는 문제가 있네요... 최대한 빨리 고치도록 하겠습니다.

**Comment by najoan125** [comment]
해결했습니다! 1.6.1로 업데이트 해보세요!

**Comment by Merhaf** [comment]
잘 작동합니다 감사합니다!!!
