### ISSUE TITLE
모드린스에서 메세지 뭐 있던 것 같은데, 뭐 하셨었나요?

### ISSUE THREAD

**Issue by shihyeon** [najoan125/fabric-koreanchat#23]
?

**Comment by najoan125** [comment]
어떤 메세지요?

**Comment by najoan125** [comment]
Description이요?

**Comment by shihyeon** [comment]
![image](https://github.com/user-attachments/assets/a0597685-a89e-47f7-a797-bc618190c8d3)
알림이 있었어서

**Comment by najoan125** [comment]
아 그 Project Settings에서 Members에서 뭐 잘못 눌러서 Member 초대 보내졌었어요

**Comment by shihyeon** [comment]
아 넵 알겠습니다
