### ISSUE TITLE
1.21.1 패브릭 API에서 한/영 키를 눌러도 영문에서 한글로 변환이 되지 않습니다.

### ISSUE THREAD

**Issue by nanan-na** [najoan125/fabric-koreanchat#26]
설치하고 나면 한/영 키가 마인크래프트 내에서 눌리지 않습니다. 키 지정을 다른 키로 하면 변환이 잘 되는 것을 확인했으나 한/영키로 지정하면 눌리질 않습니다.

**Comment by najoan125** [comment]
설정에서 한영키로 지정했을 때 키 이름이 Left-Alt 같은 형식이아니고 다른 형식으로 뜨나요?

**Comment by najoan125** [comment]
아 원인을 찾았습니다
설정에서 IME가 활성화되어 한영키가 지정되지 않는 것을 확인했습니다. IME 변환키(기본적으로 ctrl + i) 를 눌러 IME 비활성화 하면 지정이 가능합니다
최대한 빨리 고치도록 할게요
감사합니다
