### ISSUE TITLE
1.21.1 타이핑을 하다가 게임이 충돌됌

### ISSUE THREAD

**Issue by h1x-xz1n** [najoan125/fabric-koreanchat#27]
루나클라이언트로 한글채팅기능이 없어서 모드로 쓰고있는데
막상 타이핑을 하려고하면 게임이 충돌됩니다.

**Comment by najoan125** [comment]
아 알고보니 제가 바보같이 코드 고쳐놓고 업데이트를 안했네요... 바로 업데이트 하겠습니다
