### ISSUE TITLE
` Win key + . `의 이모지 창을 열고, 그것으로 이모지 입력 시 입력이 되지 않는 버그

### ISSUE THREAD

**Issue by shihyeon** [najoan125/fabric-koreanchat#7]
`Win key + .` 을 눌러 이모지를 입력하는 경우 텍스트 박스에 이모지가 입력되지 않습니다.

- 한/영 구분 없이 입력되지 않음.
- 클립보드, ctrl+c, v는 이상 없음.
- 바닐라에는 이상 없음.

**Comment by najoan125** [comment]
한영키를 이용해 전환하기 위해 ime를 비활성화해서 그렇습니다. 추후에 다른 방식으로 대체하거나 껐다 켰다 가능하게 만들 예정입니다

**Comment by shihyeon** [comment]
수정되었기에 이슈 닫겠습니다.
https://github.com/najoan125/fabric-koreanchat/commit/1889c6d03f8909a6c4d76ee41d139a323ad557a7
